### PR TITLE
Trivial cleanups, no logic changes.

### PR DESCRIPTION
**Pull request by Fraser999**
This change is [Reviewable](https://reviewable.io/reviews/dirvine/data_chain/6)

### CODE REVIEW

**Comment by dirvine** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/chain/block.rs, line 30 [r1]](https://reviewable.io:443/reviews/dirvine/data_chain/6#-KPN4e9YPi94kNjbk1HT:-KPN4e9Zg9dqndZAKFGp:bvk4xdo) ([raw file](https://github.com/dirvine/data_chain/blob/e31e24d647a144cb244ffaf91a808a0a48d668a0/src/chain/block.rs#L30)):_

> ``` Rust
> pub struct Block {
>     identifier: BlockIdentifier,
>     proofs: Vec<Proof>,
> ```

Not sure about this one actually, this is a vector of proofs where a proof is a single nodes presentation of a proof? Although the culmination of these individual proofs does become the proof itself of a block?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dirvine/data_chain/6)_

**Comment by dirvine** [comment]
Reviewed 9 of 13 files at r1.
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dirvine/data_chain/6)_

**Comment by Fraser999** [comment]
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/chain/block.rs, line 30 [r1]](https://reviewable.io:443/reviews/dirvine/data_chain/6#-KPN4e9YPi94kNjbk1HT:-KPN6UuxGYyYN6lEgPQv:b-f0e3ss) ([raw file](https://github.com/dirvine/data_chain/blob/e31e24d647a144cb244ffaf91a808a0a48d668a0/src/chain/block.rs#L30)):_
<details><summary>

<i>Previously, dirvine (David Irvine) wrote…</i></summary>



> Not sure about this one actually, this is a vector of proofs where a proof is a single nodes presentation of a proof? Although the culmination of these individual proofs does become the proof itself of a block?
> </details>
> Yeah, I see your point.  I do still feel it's easier to read as `proofs`, but I can change this back if you prefer.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dirvine/data_chain/6)_

**Comment by dirvine** [comment]
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/chain/block.rs, line 30 [r1]](https://reviewable.io:443/reviews/dirvine/data_chain/6#-KPN4e9YPi94kNjbk1HT:-KPN9-9RCsivDeNchGM1:bta7gqm) ([raw file](https://github.com/dirvine/data_chain/blob/e31e24d647a144cb244ffaf91a808a0a48d668a0/src/chain/block.rs#L30)):_
<details><summary>

<i>Previously, Fraser999 (Fraser Hutchison) wrote…</i></summary>



> Yeah, I see your point.  I do still feel it's easier to read as `proofs`, but I can change this back if you prefer.
> </details>
> Lets see what @afck  and @maqi thinks ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dirvine/data_chain/6)_

**Comment by dirvine** [comment]
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/chain/block.rs, line 30 [r1]](https://reviewable.io:443/reviews/dirvine/data_chain/6#-KPN4e9YPi94kNjbk1HT:-KPN9GqB1OO58YmZNhcJ:b8x0ymw) ([raw file](https://github.com/dirvine/data_chain/blob/e31e24d647a144cb244ffaf91a808a0a48d668a0/src/chain/block.rs#L30)):_
<details><summary>

<i>Previously, dirvine (David Irvine) wrote…</i></summary>



> Lets see what @afck  and @maqi thinks ?
> </details>
> Actually I am changing my vote for proofs here :+1: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dirvine/data_chain/6)_

**Comment by afck** [comment]
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/chain/block.rs, line 30 [r1]](https://reviewable.io:443/reviews/dirvine/data_chain/6#-KPN4e9YPi94kNjbk1HT:-KPNE3b1G-5MYDxMY8LB:b-98im4d) ([raw file](https://github.com/dirvine/data_chain/blob/e31e24d647a144cb244ffaf91a808a0a48d668a0/src/chain/block.rs#L30)):_
<details><summary>

<i>Previously, dirvine (David Irvine) wrote…</i></summary>



> Actually I am changing my vote for proofs here :+1: 
> </details>
> :thumbsup: 
> Alternatively, if we keep `proof`, I'd maybe rename `Proof` to `Signature`?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dirvine/data_chain/6)_

**Comment by Fraser999** [comment]
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/chain/block.rs, line 30 [r1]](https://reviewable.io:443/reviews/dirvine/data_chain/6#-KPN4e9YPi94kNjbk1HT:-KPNETovL1SOTJvMGw48:b7xmvea) ([raw file](https://github.com/dirvine/data_chain/blob/e31e24d647a144cb244ffaf91a808a0a48d668a0/src/chain/block.rs#L30)):_
<details><summary>

<i>Previously, afck (Andreas Fackler) wrote…</i></summary>



> :thumbsup: 
> Alternatively, if we keep `proof`, I'd maybe rename `Proof` to `Signature`?
> </details>
> Hmm, not sure on that one either.  `Proof` contains a key as well as a signature.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dirvine/data_chain/6)_

**Comment by dirvine** [comment]
:lgtm:

---

Reviewed 4 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dirvine/data_chain/6#-:-KPyJlKFEcxIIJPDmz_B:bnfp4nl)_

**Pull request merged**
